name: ci

on:
  push:
    branches:
      - 'feature'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
    
    - name: login
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    
    - name: check repo clean
      run: |
        if git diff --exit-code; then
          echo "No changes to commit."
        else
          git add . && git commit -am "new version"
        fi
    
    #- name: status
    #  run: git status    

    - name: PAIN...
      run: npm --no-git-tag-version version patch
    #    git status  
        
    #    git status  
        
    #- name: status
    #  run: git status
    - name: version status
      run: node -p "require('./package.json').version"